### ISSUE TITLE
Iron is Fe NOT Fg LOL

### ISSUE THREAD

**Issue by RealDuckteam** [KuhlTime/Periodensystem#1]
Iron is Fe not Fg LOL :D

**Comment by Floskinner** [comment]
As you can see in my PR #2 i fixed Iron. Unfortunately the explaination is now black... You are still welcome to use my fork.: https://github.com/Floskinner/Periodensystem/blob/fix/iron/Periodensystem%20-%20Farbe.pdf

![image](https://github.com/user-attachments/assets/74a63aa3-a3e5-4798-8997-fcd10f1549ba)
